# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-19 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0005_auto_20191018_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='posted_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
