# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-19 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0006_image_posted_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='feedback',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=tinymce.models.HTMLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='comments',
            field=models.CharField(max_length=35, null=True),
        ),
    ]
